"""
Pydantic schemas for Tokencast API requests/responses
"""

from datetime import datetime
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


# =============================================================================
# SHOW SCHEMAS
# =============================================================================

class ShowCreate(BaseModel):
    """Request to create a new show"""
    estimated_duration: int = Field(60, description="Show duration in minutes")


class ShowResponse(BaseModel):
    """Show details response"""
    id: int
    show_number: int
    started_at: Optional[datetime]
    ended_at: Optional[datetime]
    status: str
    estimated_duration: Optional[int]
    total_viewers: int
    created_at: datetime

    class Config:
        from_attributes = True


# =============================================================================
# SEGMENT SCHEMAS
# =============================================================================

class SegmentCreate(BaseModel):
    """Request to create a new segment"""
    show_id: int
    segment_type: str
    segment_number: int
    duration_seconds: int = Field(300, description="Segment duration (default 5 min)")


class SegmentContent(BaseModel):
    """Segment content generated by segment generators"""
    speaker_notes: str = Field(..., description="Notes for AI host/presenter")
    featured_tokens: List[Dict[str, Any]] = Field(default_factory=list)
    swarm_analyses: List[Dict[str, Any]] = Field(default_factory=list)
    metadata: Optional[Dict[str, Any]] = None


class SegmentResponse(BaseModel):
    """Segment details response"""
    id: int
    show_id: int
    segment_type: str
    segment_number: int
    started_at: Optional[datetime]
    ended_at: Optional[datetime]
    duration_seconds: Optional[int]
    status: str
    content_generated: Optional[str]
    speaker_notes: Optional[str]
    swarm_analysis_data: Optional[Dict]
    viewer_count: int
    created_at: datetime

    class Config:
        from_attributes = True


# =============================================================================
# PUMP.FUN TOKEN SCHEMAS
# =============================================================================

class TokenLaunchEvent(BaseModel):
    """Pump.fun token launch event"""
    token_address: str
    ticker: Optional[str]
    mint_address: Optional[str]
    price_at_discovery: Optional[float]
    discovered_at: datetime
    bonding_curve_address: Optional[str]
    social_links: Optional[Dict[str, str]] = None


class TokenStatusResponse(BaseModel):
    """Current token status"""
    token_address: str
    ticker: Optional[str]
    current_price: Optional[float]
    market_cap: Optional[float]
    holders_count: Optional[int]
    volume_24h: Optional[float]
    tracking_status: str
    bonding_curve_address: Optional[str]
    last_tracked_at: Optional[datetime]

    class Config:
        from_attributes = True


class TokenAnalyzeRequest(BaseModel):
    """Request to analyze a token with SWARM"""
    token_address: str
    ticker: str


class TokenAnalyzeResponse(BaseModel):
    """Token analysis result from SWARM"""
    token_address: str
    ticker: str
    regime: str
    narrative_phase: str
    risk_score: float
    divergence_detected: bool
    analysis_timestamp: datetime


# =============================================================================
# COMMUNITY INTERACTION SCHEMAS
# =============================================================================

class CommunityInteractionCreate(BaseModel):
    """Log a community interaction"""
    show_id: int
    segment_id: Optional[int]
    user_id: str
    interaction_type: str  # poll_vote, chat_message, token_mention, reaction
    content: Optional[str]
    metadata: Optional[Dict[str, Any]]


# =============================================================================
# METRICS SCHEMAS
# =============================================================================

class MetricCreate(BaseModel):
    """Create a metric"""
    show_id: int
    metric_name: str
    metric_value: float
    metadata: Optional[Dict[str, Any]]


class ShowMetricsResponse(BaseModel):
    """Show analytics"""
    show_id: int
    total_viewers_peak: Optional[int]
    total_interactions: int
    tokens_featured: int
    average_segment_duration: Optional[float]
    segment_breakdown: Dict[str, int]
